export enum StatusPedido {
  AGUARDANDO_ACEITE = 'AGUARDANDO_ACEITE',
  EM_PREPARO = 'EM_PREPARO',
  AGUARDANDO_MOTORISTA = 'AGUARDANDO_MOTORISTA',
  A_CAMINHO = 'A_CAMINHO',
  ENTREGUE = 'ENTREGUE',
  CANCELADO = 'CANCELADO',
}
